phases:
  install:
    runtime-versions:
      nodejs: 14  # Adjust to your project's required Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building application..."
      - npm run build

artifacts:
  paths:
    - build/**  # Include only the build directory
