version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Choose the Node.js version appropriate for your project
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
