version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Choose the Node.js version appropriate for your project
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Checking installed node modules..."
      - ls -la node_modules/.bin
      - ls -la node_modules/react-scripts/bin
  build:
    commands:
      - echo "Build started on `date`"
      - npm run build
artifacts:
  files:
    - '**/*'
